from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True, slots=True)
class DirectorySpec:
    legacy_dir: str
    python_dir: str
    kind: str


@dataclass(frozen=True, slots=True)
class FileSpec:
    legacy_file: str
    python_file: str
    required: bool


DIRECTORY_SPECS: tuple[DirectorySpec, ...] = (
    DirectorySpec("EFPS", "efps", "graphics"),
    DirectorySpec("FNTS", "fnts", "graphics"),
    DirectorySpec("LEVS", "levs", "level"),
    DirectorySpec("MUSIC", "music", "sound"),
    DirectorySpec("WAVS", "wavs", "sound"),
)

FILE_SPECS: tuple[FileSpec, ...] = (
    FileSpec("PALETTE.TAB", "palette.tab", True),
    FileSpec("OPTIONS.CFG", "options.cfg", False),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate python/game_data asset manifest and gap list",
    )
    parser.add_argument(
        "--legacy-root",
        type=Path,
        default=None,
        help="Optional path containing original EFPS/FNTS/LEVS/MUSIC/WAVS",
    )
    parser.add_argument(
        "--python-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Path to the python/ directory",
    )
    return parser.parse_args()


def _sorted_relative_files(directory: Path) -> list[str]:
    files: list[str] = []
    for path in directory.rglob("*"):
        if path.is_file():
            files.append(path.relative_to(directory).as_posix())
    files.sort()
    return files


def _casefold_index(files: list[str]) -> dict[str, str]:
    return {entry.upper(): entry for entry in files}


def _dir_report(legacy_dir: Path, python_dir: Path) -> dict[str, object]:
    legacy_files = _sorted_relative_files(legacy_dir)
    python_files = _sorted_relative_files(python_dir)
    legacy_index = _casefold_index(legacy_files)
    python_index = _casefold_index(python_files)

    missing = [legacy_index[key] for key in sorted(legacy_index.keys() - python_index.keys())]
    extra = [python_index[key] for key in sorted(python_index.keys() - legacy_index.keys())]

    return {
        "legacy_count": len(legacy_files),
        "python_count": len(python_files),
        "missing_in_python": missing,
        "extra_in_python": extra,
        "legacy_files": legacy_files,
        "python_files": python_files,
    }


def _render_gap_markdown(
    categories: dict[str, dict[str, object]],
    standalone_files: dict[str, dict[str, object]],
    compare_mode: str,
) -> str:
    lines: list[str] = []
    lines.append("# Asset Manifest Gap List")
    lines.append("")
    lines.append("This report is generated by `python/tools/asset_manifest_report.py`.")
    lines.append("")
    if compare_mode == "legacy_compare":
        lines.append("Comparison mode: `legacy_compare` (python/game_data compared against legacy source root).")
    else:
        lines.append("Comparison mode: `python_only` (no legacy source root required).")
    lines.append("")
    lines.append("## Source mapping")
    lines.append("")
    lines.append("- Graphical assets: `EFPS/`, `FNTS/` -> `python/game_data/efps/`, `python/game_data/fnts/`")
    lines.append("- Sound assets: `MUSIC/`, `WAVS/` -> `python/game_data/music/`, `python/game_data/wavs/`")
    lines.append("- Level assets: `LEVS/` -> `python/game_data/levs/`")
    lines.append("- Standalone files: `PALETTE.TAB`, `OPTIONS.CFG`")
    lines.append("")
    lines.append("## Category comparison")
    lines.append("")
    lines.append("| Category | Kind | Legacy | Python | Missing | Extra |")
    lines.append("| --- | --- | ---: | ---: | ---: | ---: |")
    for category_name, category in categories.items():
        lines.append(
            "| "
            f"{category_name} | {category['kind']} | {category['legacy_count']} | {category['python_count']} | "
            f"{len(category['missing_in_python'])} | {len(category['extra_in_python'])} |",
        )
    lines.append("")
    lines.append("## Missing in python/game_data")
    lines.append("")
    for category_name, category in categories.items():
        lines.append(f"### {category_name}")
        missing = category["missing_in_python"]
        if missing:
            for file_path in missing:
                lines.append(f"- {file_path}")
        else:
            lines.append("- None")
        lines.append("")
    lines.append("## Extra files in python/game_data")
    lines.append("")
    for category_name, category in categories.items():
        lines.append(f"### {category_name}")
        extra = category["extra_in_python"]
        if extra:
            for file_path in extra:
                lines.append(f"- {file_path}")
        else:
            lines.append("- None")
        lines.append("")
    lines.append("## Standalone file status")
    lines.append("")
    for name, report in standalone_files.items():
        status = "present" if report["python_exists"] else "missing"
        required = "required" if report["required"] else "optional"
        lines.append(f"- {name}: {status} ({required})")
    lines.append("")
    lines.append(
        "Graphical and sound assets are considered migration-complete when all "
        "missing/extra counts are zero.",
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    legacy_root = args.legacy_root.expanduser().resolve() if args.legacy_root else None
    compare_mode = "legacy_compare" if legacy_root is not None else "python_only"
    python_root = args.python_root.expanduser().resolve()
    game_data_root = python_root / "game_data"

    categories: dict[str, dict[str, object]] = {}
    required_files: list[str] = []
    required_graphics_sound_files: list[str] = []

    for spec in DIRECTORY_SPECS:
        python_dir = game_data_root / spec.python_dir
        if not python_dir.is_dir():
            raise FileNotFoundError(f"missing python asset directory: {python_dir}")

        if legacy_root is None:
            python_files = _sorted_relative_files(python_dir)
            report = {
                "legacy_count": len(python_files),
                "python_count": len(python_files),
                "missing_in_python": [],
                "extra_in_python": [],
                "legacy_files": python_files,
                "python_files": python_files,
            }
        else:
            legacy_dir = legacy_root / spec.legacy_dir
            if not legacy_dir.is_dir():
                raise FileNotFoundError(f"missing legacy asset directory: {legacy_dir}")
            report = _dir_report(legacy_dir, python_dir)

        report["kind"] = spec.kind
        report["legacy_dir"] = spec.legacy_dir
        report["python_dir"] = spec.python_dir
        report["compare_mode"] = compare_mode
        categories[f"{spec.legacy_dir}->{spec.python_dir}"] = report

        required_files.extend(f"{spec.python_dir}/{entry}" for entry in report["legacy_files"])
        if spec.kind in {"graphics", "sound"}:
            required_graphics_sound_files.extend(
                f"{spec.python_dir}/{entry}" for entry in report["legacy_files"]
            )

    standalone_files: dict[str, dict[str, object]] = {}
    optional_files: list[str] = []
    for spec in FILE_SPECS:
        legacy_path = legacy_root / spec.legacy_file if legacy_root is not None else None
        python_path = game_data_root / spec.python_file
        report = {
            "legacy_file": spec.legacy_file,
            "python_file": spec.python_file,
            "required": spec.required,
            "legacy_exists": legacy_path.is_file() if legacy_path is not None else None,
            "python_exists": python_path.is_file(),
            "compare_mode": compare_mode,
        }
        standalone_files[spec.legacy_file] = report
        if spec.required:
            required_files.append(spec.python_file)
        else:
            optional_files.append(spec.python_file)

    required_files = sorted(set(required_files))
    required_graphics_sound_files = sorted(set(required_graphics_sound_files))
    optional_files = sorted(set(optional_files))

    manifest = {
        "manifest_version": 1,
        "generated_by": "python/tools/asset_manifest_report.py",
        "compare_mode": compare_mode,
        "required_files": required_files,
        "required_graphics_sound_files": required_graphics_sound_files,
        "optional_files": optional_files,
        "categories": categories,
        "standalone_files": standalone_files,
    }

    manifest_path = game_data_root / "asset_manifest.json"
    manifest_path.write_text(f"{json.dumps(manifest, indent=2)}\n", encoding="utf-8")

    gap_report = _render_gap_markdown(
        categories=categories,
        standalone_files=standalone_files,
        compare_mode=compare_mode,
    )
    gap_report_path = game_data_root / "asset_manifest_gap_list.md"
    gap_report_path.write_text(gap_report, encoding="utf-8")

    print(f"wrote {manifest_path}")
    print(f"wrote {gap_report_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
